
import { Product, Language } from './types';

// =====================================================================
// 🖼️ GLOBAL MEDIA LIBRARY (ASSETS) | 图片资源库
// =====================================================================
export const ASSETS = {
  HERO: {
    MAIN: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?q=80&w=2000&auto=format&fit=crop',
  },
  CATEGORY: {
    MALE: 'https://i.ibb.co/MkxwX2kZ/Chat-GPT-Image-2025-12-17-01-01-42-1.png',
    FEMALE: 'https://i.ibb.co/VWjDCLqN/F9-F82-ABA-2-D08-4259-B455-90-EF48868-A5-D.jpg',
  },
  PHILOSOPHY: {
    ORIGIN: 'https://images.unsplash.com/photo-1599148401005-fe6d75f68c32?q=80&w=1000&auto=format&fit=crop',
    MATERIAL: 'https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?q=80&w=1000&auto=format&fit=crop',
    TAILOR: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?q=80&w=2000&auto=format&fit=crop',
  },
  OCCASIONS: {
    HOME: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?q=80&w=800&auto=format&fit=crop',
    WALK: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?q=80&w=800&auto=format&fit=crop',
    RAIN: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=800&auto=format&fit=crop',
    SLEEP: 'https://images.unsplash.com/photo-1541781777631-fa9537171859?q=80&w=800&auto=format&fit=crop',
  },
  MANAGER: {
    AVATAR: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=800&auto=format&fit=crop',
  },
  MODELS: {
    WHITE: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=800&auto=format&fit=crop',
    APRICOT: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?q=80&w=800&auto=format&fit=crop',
    BLACK: 'https://images.unsplash.com/photo-1620021673322-26f6345dc553?q=80&w=800&auto=format&fit=crop',
  },
  PRODUCTS: {
    TEE: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=1000&auto=format&fit=crop',
    HOODIE: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=800&auto=format&fit=crop',
    STRIPE: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=1000&auto=format&fit=crop',
    VEST: 'https://images.unsplash.com/photo-1517423568366-6975535403b3?q=80&w=1000&auto=format&fit=crop',
    TRENCH: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?q=80&w=1000&auto=format&fit=crop',
    LEASH_L: 'https://images.unsplash.com/photo-1629898038755-6b589434860b?q=80&w=1000&auto=format&fit=crop',
    LEASH_R: 'https://images.unsplash.com/photo-1551529834-525807d6b4f3?q=80&w=1000&auto=format&fit=crop',
    COLLAR_P: 'https://images.unsplash.com/photo-1605218427360-36390f85b34c?q=80&w=1000&auto=format&fit=crop',
    COLLAR_L: 'https://images.unsplash.com/photo-1598583486847-c0258074d0a9?q=80&w=1000&auto=format&fit=crop',
    BOWTIE: 'https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?q=80&w=1000&auto=format&fit=crop',
    HAIRCLIP: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=1000&auto=format&fit=crop',
    DRESS: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=1000&auto=format&fit=crop',
    BOWL: 'https://images.unsplash.com/photo-1585846416120-3a7354ed7d6d?q=80&w=1000&auto=format&fit=crop',
    BOTTLE: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?q=80&w=1000&auto=format&fit=crop',
    RAIN_CLEAR: 'https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?q=80&w=1000&auto=format&fit=crop',
    BED: 'https://images.unsplash.com/photo-1541781777631-fa9537171859?q=80&w=1000&auto=format&fit=crop',
    CARRIER: 'https://images.unsplash.com/photo-1601758003122-53c40e686a19?q=80&w=1000&auto=format&fit=crop',
  },
  GALLERY_DETAILS: [
    'https://images.unsplash.com/photo-1599148401005-fe6d75f68c32?q=80&w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?q=80&w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1598133869164-6eb75f380f70?q=80&w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=800&auto=format&fit=crop'
  ]
};

export const NAV_LINKS = [
  { label: { EN: 'Boy', JP: '男の子', ZH_TW: '公狗' }, value: 'MALE' },
  { label: { EN: 'Girl', JP: '女の子', ZH_TW: '母狗' }, value: 'FEMALE' },
  { label: { EN: 'Philosophy & Craft', JP: '理念と工芸', ZH_TW: '理念與工藝' }, value: 'PHILOSOPHY' },
];

export const CATEGORY_FILTERS = [
  { id: 'ALL', label: { EN: 'All', JP: 'すべて', ZH_TW: '全部' } },
  { id: 'CLOTHING', label: { EN: 'Clothing', JP: 'ウェア', ZH_TW: '衣服' } },
  { id: 'LEASH', label: { EN: 'Leashes', JP: 'リード', ZH_TW: '牽引繩' } },
  { id: 'COLLAR', label: { EN: 'Collars', JP: '首輪', ZH_TW: '項圈' } },
  { id: 'ACCESSORY', label: { EN: 'Accessories', JP: 'アクセサリー', ZH_TW: '配飾' } },
  { id: 'BOWL', label: { EN: 'Bowls', JP: 'フードボウル', ZH_TW: '狗碗' } },
  { id: 'DISPENSER', label: { EN: 'Water', JP: '給水器', ZH_TW: '飲水器' } },
];

export const INFO_LINKS = [
  { 
    id: 'size-guide', 
    label: { EN: 'Size Guide', JP: '犬種とサイズの測り方', ZH_TW: '犬種與尺寸測量' },
    content: { EN: "...", JP: "...", ZH_TW: "..." }
  },
  { 
    id: 'contact', 
    label: { EN: 'Contact Us', JP: 'お問い合わせ', ZH_TW: '聯絡我們' },
    content: { EN: '...', JP: '...', ZH_TW: '...' }
  }
];

export const TRANSLATIONS = {
  EN: {
    heroSlogan: 'Haute Couture for the 2.5kg Silhouette.',
    newIn: 'New Arrivals',
    viewAll: 'View All',
    titleMale: 'Collection for Boys',
    subMale: 'Cool & Functional',
    titleFemale: 'Collection for Girls',
    subFemale: 'Elegant & Soft',
    footerCopy: '© 2025 MOKO BASIC',
    aiWelcome: 'Bonjour. I am your Moko Concierge.',
    newBadge: 'Nouveau',
    buyAmazon: 'Visit Amazon Store',
    buyRakuten: 'Visit Rakuten Store',
    sizeGuide: 'Moko Fit Finder',
    specs: { warmth: 'Warmth', breathability: 'Breathability', stretch: 'Stretch', softness: 'Softness' },
    // Registration / Login
    loginTitle: 'Member Registration',
    loginBack: 'Return to Shop',
    loginAmazonBtn: 'Login with Amazon',
    loginAmazonSub: 'Login easily with Amazon linkage!',
    loginAmazonDesc: 'You can register using your Amazon account information.',
    loginManualTitle: 'Please enter the necessary information in the form below.',
    loginManualNote: 'Your email address will be your login ID.',
    loginRequired: 'is a required item',
    loginName: 'Name',
    loginNameFuri: 'Name (Furigana)',
    loginEmail: 'Email Address',
    loginEmailConfirm: 'Confirm Email Address',
    loginPassword: 'Password',
    loginPasswordConfirm: 'Confirm Password',
    loginNewsletter: 'Email Magazine',
    loginOptIn: 'Subscribe',
    loginOptOut: 'No Thanks',
    loginGender: 'Gender',
    loginMale: 'Male',
    loginFemale: 'Female',
    loginNoAnswer: 'No Answer',
    loginBirth: 'Birthdate',
    loginPhone: 'Phone Number',
    loginZip: 'Postal Code',
    loginPref: 'Prefecture',
    loginCity: 'Municipality',
    loginAddress: 'Address line 2',
    loginMobile: 'Mobile Phone',
    loginReferrer: 'Referrer ID',
    loginReferrerDesc: '*Member Email Address',
    loginPrefPlaceholder: 'Please select',
    loginPlaceholderName: 'Example) Taro Yamada',
    loginPlaceholderFuri: 'Example) YAMADA TARO',
    loginPlaceholderBirth: 'Example) 19940101',
    loginTerms: 'Agree to Membership Terms and Privacy Policy',
    loginSubmit: 'Register with this content',
    // Contact Form
    contactTitle: 'Contact Us',
    contactInstruction: 'Please enter the following form fields and click the "Inquire with this content" button.',
    contactGmailNoticeTitle: 'For customers using Gmail',
    contactGmailNoticeBody: 'Since February 2024, Gmail has significantly strengthened its measures against spam. Due to this, emails from our shop may be sent to your spam folder or not received. We request you to whitelist our domain "info@mokobasic.tokyo".',
    contactLabelName: 'Name',
    contactLabelEmail: 'Email Address',
    contactLabelBody: 'Inquiry Content',
    contactRequired: 'Required',
    contactCharLimit: 'Up to 2000 characters',
    contactPrivacyTitle: 'Privacy Policy',
    contactPrivacyAgree: 'I agree to the privacy policy',
    contactSubmit: 'Inquire with this content',
    journalSub: 'Stories from the Atelier',
    readStory: 'Read Story',
    shopMemory: 'Shop This Memory',
    // Fitting Room
    fittingTitle: 'Virtual Fitting Room',
    fittingSub: 'Visualize our collection on your Teddy',
    fittingCoat: 'Select Coat Color',
    fittingFabric: 'Select Fabric',
    fittingReset: 'Reset Selection'
  },
  JP: {
    heroSlogan: '2.5kgのための、オートクチュール。',
    newIn: '最新のクリエーション',
    viewAll: 'すべて見る',
    titleMale: '男の子コレクション',
    subMale: 'クール & 機能的',
    titleFemale: '女の子コレクション',
    subFemale: 'エレガント & ソフト',
    footerCopy: '© 2025 MOKO BASIC',
    aiWelcome: 'Bonjour. Mokoコンシェルジュです。',
    newBadge: '新作',
    buyAmazon: 'Amazonで購入',
    buyRakuten: '楽天で購入',
    sizeGuide: 'Moko サイズ診断',
    specs: { warmth: '暖かさ', breathability: '通気性', stretch: '伸縮性', softness: '柔らかさ' },
    // Registration / Login
    loginTitle: '会員情報登録',
    loginBack: 'ショップへ戻る',
    loginAmazonBtn: 'Amazon でログイン',
    loginAmazonSub: 'Amazon連携で簡単ログイン！',
    loginAmazonDesc: 'Amazonアカウントに登録されている会員情報を使用して新規会員登録が可能です。',
    loginManualTitle: '以下のフォームに必要事項をご入力ください。',
    loginManualNote: 'ログイン時のIDはメールアドレスをご利用ください。',
    loginRequired: 'は入力必須項目です',
    loginName: 'お名前',
    loginNameFuri: 'お名前（フリガナ）',
    loginEmail: 'メールアドレス',
    loginEmailConfirm: 'メールアドレス確認',
    loginPassword: 'パスワード',
    loginPasswordConfirm: 'パスワード確認',
    loginNewsletter: 'メールマガジン',
    loginOptIn: '希望します。',
    loginOptOut: '希望しません。',
    loginGender: '性別',
    loginMale: '男',
    loginFemale: '女',
    loginNoAnswer: '無回答',
    loginBirth: '生年月日',
    loginPhone: '電話番号',
    loginZip: '郵便番号',
    loginPref: '都道府県',
    loginCity: '市区町村',
    loginAddress: 'それ以降の住所',
    loginMobile: '携帯電話番号',
    loginReferrer: '紹介者ID',
    loginReferrerDesc: '※会員メールアドレス',
    loginPrefPlaceholder: '選択してください',
    loginPlaceholderName: '例）山田太郎',
    loginPlaceholderFuri: '例）ヤマダタロウ',
    loginPlaceholderBirth: '例）19940101',
    loginTerms: '上記会員規約、個人情報の取り扱いについて同意する',
    loginSubmit: 'この内容で会員登録する',
    // Contact Form
    contactTitle: 'お問い合わせ',
    contactInstruction: '以下のフォームの項目を入力し、よろしければ「この内容で問い合わせる」ボタンをクリックしてください。',
    contactGmailNoticeTitle: 'Gmailをご利用のお客様',
    contactGmailNoticeBody: '2024年2月以降、Gmailでは迷惑メール（なりすましメール）対策を大幅に強化いたしました。上記にともない、当ショップからのメールが迷惑メールフォルダまたは着信しないとのご連絡をいただいております。当ショップからのメール「info@mokobasic.tokyo」の受信設定をお願いいたします。',
    contactLabelName: 'お名前',
    contactLabelEmail: 'メールアドレス',
    contactLabelBody: 'お問い合わせ内容',
    contactRequired: '必須',
    contactCharLimit: '※全角2000文字まで',
    contactPrivacyTitle: '個人情報保護ポリシー',
    contactPrivacyAgree: '個人情報保護ポリシーに同意する',
    contactSubmit: 'この内容で問い合わせる',
    journalSub: 'アトリエからの物語',
    readStory: 'ストーリーを読む',
    shopMemory: 'このメモリーを購入',
    // Fitting Room
    fittingTitle: 'バーチャルフィッティング',
    fittingSub: '愛犬にぴったりのカラーを見つけましょう',
    fittingCoat: '毛色を選択',
    fittingFabric: '生地を選択',
    fittingReset: 'リセット'
  },
  ZH_TW: {
    heroSlogan: '為 2.5kg 體型打造的高級訂製。',
    newIn: '最新商品',
    viewAll: '查看全部',
    titleMale: '公犬系列',
    subMale: '帥氣 & 機能',
    titleFemale: '母犬系列',
    subFemale: '優雅 & 柔軟',
    footerCopy: '© 2025 MOKO BASIC',
    aiWelcome: 'Bonjour. 我是您的 Moko 專屬顧問。',
    newBadge: '新作',
    buyAmazon: '前往 Amazon',
    buyRakuten: '前往樂天',
    sizeGuide: 'Moko 尺寸診斷',
    specs: { warmth: '保暖性', breathability: '透氣性', stretch: '彈性', softness: '柔軟度' },
    // Registration / Login
    loginTitle: '會員註冊',
    loginBack: '返回商店',
    loginAmazonBtn: '使用 Amazon 登入',
    loginAmazonSub: '連結 Amazon 輕鬆登入！',
    loginAmazonDesc: '您可以使用 Amazon 帳戶中註冊的會員資訊進行新會員註冊。',
    loginManualTitle: '請在下方表單中輸入必要資訊。',
    loginManualNote: '登入時請使用電子郵件地址作為 ID。',
    loginRequired: '為必填項目',
    loginName: '姓名',
    loginNameFuri: '姓名（注音/拼音）',
    loginEmail: '電子郵件地址',
    loginEmailConfirm: '確認電子郵件',
    loginPassword: '密碼',
    loginPasswordConfirm: '確認密碼',
    loginNewsletter: '電子報訂閱',
    loginOptIn: '我希望訂閱',
    loginOptOut: '我不希望訂閱',
    loginGender: '性別',
    loginMale: '男',
    loginFemale: '女',
    loginNoAnswer: '不便回答',
    loginBirth: '生年月日',
    loginPhone: '電話號碼',
    loginZip: '郵遞區號',
    loginPref: '縣市/都道府縣',
    loginCity: '市區村里',
    loginAddress: '詳細地址',
    loginMobile: '行動電話',
    loginReferrer: '介紹人 ID',
    loginReferrerDesc: '*會員電子郵件',
    loginPrefPlaceholder: '請選擇',
    loginPlaceholderName: '例）山田太郎',
    loginPlaceholderFuri: '例）YAMADA TARO',
    loginPlaceholderBirth: '例）19940101',
    loginTerms: '我同意上述會員規約與個人隱私權政策',
    loginSubmit: '以此內容完成註冊',
    // Contact Form
    contactTitle: '聯絡我們',
    contactInstruction: '請填寫以下表單項目，確認無誤後點擊「以此內容送出諮詢」按鈕。',
    contactGmailNoticeTitle: '使用 Gmail 的客戶',
    contactGmailNoticeBody: '自 2024 年 2 月起，Gmail 大幅加強了對垃圾郵件的過濾。因此，本商店的郵件可能會被歸類到垃圾郵件箱或無法送達。請務必將「info@mokobasic.tokyo」加入您的白名單。',
    contactLabelName: '姓名',
    contactLabelEmail: '電子郵件地址',
    contactLabelBody: '諮詢內容',
    contactRequired: '必須',
    contactCharLimit: '※ 2000 字以內',
    contactPrivacyTitle: '個人隱私權政策',
    contactPrivacyAgree: '我同意個人隱私權政策',
    contactSubmit: '以此內容送出諮詢',
    journalSub: '來自工坊的故事',
    readStory: '閱讀故事',
    shopMemory: '購買此回憶',
    // Fitting Room
    fittingTitle: '虛擬試衣間',
    fittingSub: '為您的寶貝挑選最合適的顏色',
    fittingCoat: '選擇毛色',
    fittingFabric: '選擇面料',
    fittingReset: '重置選擇'
  }
};

export const RAW_PRODUCTS = [
  {
    id: 'e1',
    name: { EN: 'Pure Cotton Tee', JP: 'ピュアコットンTシャツ', ZH_TW: '純淨棉質 T 恤' },
    category: { EN: 'Tricot', JP: 'ニット', ZH_TW: '針織' },
    subcategory: 'ESSENTIALS',
    price: 1900,
    image: ASSETS.PRODUCTS.TEE, 
    tags: ['Cotton', 'Basic'],
    description: { EN: '100% Organic Cotton.', JP: 'オーガニックコットン100%。', ZH_TW: '100% 有機棉。' },
    layout: 'normal',
    specs: { warmth: 30, breathability: 95, stretch: 80, softness: 90 },
    amazonUrl: 'https://amazon.co.jp',
    rakutenUrl: 'https://rakuten.co.jp',
    gender: 'UNISEX',
    productType: 'CLOTHING'
  }
];

export const getProducts = (lang: Language): Product[] => {
  return RAW_PRODUCTS.map(p => ({
    ...p,
    name: (p.name as any)[lang],
    category: (p.category as any)[lang],
    description: (p.description as any)[lang],
    subcategory: p.subcategory as any,
    specs: p.specs,
    gender: p.gender as any,
    productType: p.productType as any,
    layout: p.layout as any
  }));
};

export const OCCASIONS = [
  { id: 'home', image: ASSETS.OCCASIONS.HOME, title: { EN: 'Relaxing Pajamas', JP: 'パジャマ', ZH_TW: '居家服' }, sub: { EN: 'Home', JP: 'おうち時間', ZH_TW: '居家' } },
  { id: 'walk', image: ASSETS.OCCASIONS.WALK, title: { EN: 'Daily Essentials', JP: 'お散歩ウェア', ZH_TW: '散步必備' }, sub: { EN: 'Walk', JP: 'お散歩', ZH_TW: '散步' } },
  { id: 'rain', image: ASSETS.OCCASIONS.RAIN, title: { EN: 'Rain Protection', JP: 'レインコート', ZH_TW: '雨衣' }, sub: { EN: 'Rain', JP: '雨の日', ZH_TW: '雨天' } },
  { id: 'sleep', image: ASSETS.OCCASIONS.SLEEP, title: { EN: 'Deep Sleep', JP: '熟睡ニット', ZH_TW: '熟睡針織' }, sub: { EN: 'Sleep', JP: '睡眠', ZH_TW: '睡眠' } }
];
